apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment

  labels:
    app: backend

  namespace: playnest

spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: utej8553/playnest-backend:latest
        ports:
        - containerPort: 5000

        env:
        - name: MONGO_URI
          value: mongodb://mongo-service:27017/playnest
        - name: JWT_SECRET
          value: mysecret
        - name: PORT
          value: "5000"

